In [11]:
import pandas as pd
import seaborn as sns
from scipy.stats import f_oneway

In [12]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [13]:
df = df[["age", "pclass"]].dropna()

In [14]:
df['pclass'].value_counts()

pclass
3    355
1    186
2    173
Name: count, dtype: int64

In [15]:
class_1 = df[df["pclass"] == 1]["age"]
class_2 = df[df["pclass"] == 2]["age"]
class_3 = df[df["pclass"] == 3]["age"]

In [16]:
f_stats, p_value = f_oneway(class_1, class_2, class_3)

In [17]:
f_stats

np.float64(57.44348434067624)

In [18]:
p_value

np.float64(7.487984171959213e-24)

In [19]:
alpha = 0.05

In [20]:
if p_value < alpha:
    print("Reject the null hypothesis")
else:
  print("Failed to reject null hypothesis")

Reject the null hypothesis